### ISSUE TITLE
El gas loop de toxinas a la burn chamber no funciona y vuelve difícil crear las bombas de plasma/oxigeno.

### ISSUE THREAD

**Issue by Box2444** [HispaniaSS13/ParadiseHispania#106]
**Issue Description**:

Los pipes de toxinas que llevan al heat exchanger del gas chamber no funcionan, drenan el canister y no se puede usar para calentar plasma como seria lo esperado aun cuando el pipe valve que habilita ese acceso este abierto.
![dreamseeker_DDjrIfXRZk](https://user-images.githubusercontent.com/88724203/218638752-70acf077-bd4b-4df4-8bf0-e6caf352573d.png)

**What did you expect to happen**: 

el plasma del canister iria al heat exchanger dentro del burn chamber y se calentaria y volveria al canister original.

**What happened instead**:

desaparece la mitad del gas dentro del canister y se queda trabado en estos dos pipes sin pasar al burn chamber
![dreamseeker_A8EPqmZLFV](https://user-images.githubusercontent.com/88724203/218638904-3a14bf9e-6292-4bfc-8d10-7d57b3b0be02.png)

**Why is this bad/What are the consequences**:

Este problema vuelve a toxinas bastante difícil de usar sin manualmente modificar los pipes.

**Steps to reproduce the problem**:

1- agarrar un canister
2- ir a toxinas y usar un wrench en el canister sobre el port 
3- abrir el pipe valve que da a la burn chamber
4- el medidor del burn chamber no indica que esta circulando gas

**When did the problem start happening**:

ni idea (mas o menos 1 mes capas 2 ?)

**Extra information**:

los pipes que traen el problema parecen ser 'insulated pipe fittings' si los sacas y pones pipes normales el port funciona normal de la manera esperada. 
![dreamseeker_JOrEDqqb22](https://user-images.githubusercontent.com/88724203/218638075-2d990a47-5b1b-4aad-9a1e-876df023f51b.png)

**Comment by Tilk1** [comment]
Este problema deberia estar resuelto por favor revisa si sigue ocurriendo con los cambios en el mapa

**Comment by Box2444** [comment]
lo probe y parece seguir con el mismo problema

**Comment by MrPink-bit** [comment]
Ya se actualizo el server?

**Comment by Tilk1** [comment]
Si, entonces habra q corregir esa zona en especifica desde mapeo

**Comment by MrPink-bit** [comment]
Estaba viendo las imágenes. Y los conectaste mal. Se debe conectar en el de bien a la izquierda, no el del medio. Una vez conectado al de bien a la izquierda. Abre la válvula y ya funciona

**Comment by MrPink-bit** [comment]
Ese del medio sirve para sacarlo al espacio si mal no me acuerdo

**Comment by Box2444** [comment]
esta bien conectado, el valve del medio literalmente se llava PORT TO HEAT EXCHANGER, ya lo hice muchisimas veces asi que estoy seguro que es ese port no te preocupes.

**Comment by MrPink-bit** [comment]
> 

Te estoy diciendo que no. Varias veces lo hice y no es como indicas

**Comment by MrPink-bit** [comment]
Te invito a entrar en 5 minutos y te lo muestro IG

**Comment by Box2444** [comment]
creo que ya se que decis, creo que funciona entonces, mala mia.
