### ISSUE TITLE
PROBLEMAS EN ATMOS y otros

### ISSUE THREAD

**Issue by MrPink-bit** [HispaniaSS13/ParadiseHispania#113]
he notado como al entrar en las maquinas de Atmos, estas en la parte del sensor indica que el tanke no funciona (se me hace que le falta dicho sensor), probocando asi que no salga dicho gas para poder ser usado. tambien he notado una puerta mal colocada, o SMES mal puesto

![bug](https://user-images.githubusercontent.com/69596970/219825957-e4766415-40c0-443f-bb2f-accb41ecfa2e.PNG)
![mal puesto](https://user-images.githubusercontent.com/69596970/219825998-69cffbd2-27f2-4a99-9adf-51847ff7bbde.PNG)

**Comment by Tilk1** [comment]
Esperemos se arregle con la update de ahora, hay  cambios al mapa y a toda la atmos

**Comment by MrPink-bit** [comment]
he notado tambien que no le llega energia a bridge, hay que ver en donde se corrta

**Comment by MrPink-bit** [comment]
otro mas es que al menos la ultima ves y ahora, no marca la posicion de las personas en el mapa de los sensores, y ahora siquiera carga el mapa

**Comment by Tilk1** [comment]
Lo del mapa u otras cosas no relacionadas a atos te invito que lo hagas en un ISSUE aparte para poder darlo por solucionado eventualmente

**Comment by MrPink-bit** [comment]
Ah bueno, bueno. Es que no quería llenar de issues. No sea que se terminan molestando

**Comment by Tilk1** [comment]
Este problema deberia ya estar resuelto
